### ISSUE TITLE
adding value from next array

### ISSUE THREAD

**Issue by klhall1987** [ClevPHP/code-kata-bowling#1]
I'm not being able to get the value from my next array. I can can't seem to get the values to come back. I just keep either double or tripling my current score. Any help would be greatly appreciated.

**Comment by kjohnson** [comment]
You are mixing the logic of the `for` loop and the `foreach` loop.

**Comment by klhall1987** [comment]
Thanks, for the advice. I think I got it figured out. I still used the array_chunk function. I need to look at alternatives to this soon. My code is up in the repository, if you don't mind taking a look at it. I still need to multiple strike logic. After that I think I will be done.
